#!/usr/bin/env tsx
/**
 * theme-export.ts
 *
 * Reads `packages/tokens/src/rehab-tokens.json` and emits:
 *   - packages/tokens/src/tokens.css   (canonical M3 CSS variables)
 *   - packages/tokens/src/tokens.d.ts  (typed export for TS)
 *
 * The current rehab-tokens.json is hand-authored to match the
 * material-theme-builder export. Running this script keeps the
 * CSS in lock-step with the JSON.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const tokensPath = join(root, 'packages/tokens/src/rehab-tokens.json');
const cssOut = join(root, 'packages/tokens/src/tokens.css');
const dtsOut = join(root, 'packages/tokens/src/tokens.d.ts');

type Scheme = Record<string, string>;

interface Tokens {
  schemes: { light: Scheme; dark: Scheme };
  surfaces?: { light: Scheme; dark: Scheme };
  fixedAccents?: Scheme;
}

const tokens: Tokens = JSON.parse(readFileSync(tokensPath, 'utf8'));

function kebab(s: string): string {
  return s.replace(/([A-Z])/g, '-$1').toLowerCase();
}

function buildBlock(
  selector: string,
  prefix: string,
  map: Scheme | undefined,
  comment?: string,
): string[] {
  const out: string[] = [];
  out.push(selector + ' {');
  if (comment) out.push(`  /* ${comment} */`);
  for (const [role, value] of Object.entries(map ?? {})) {
    if (role.startsWith('_')) continue;
    out.push(`  ${prefix}${kebab(role)}: ${value};`);
  }
  out.push('}');
  return out;
}

const blocks: string[] = [];
blocks.push('/*');
blocks.push(' * Rehab Store — Material 3 design tokens.');
blocks.push(' * AUTO-GENERATED by scripts/theme-export.ts — do not edit by hand.');
blocks.push(' * Source: packages/tokens/src/rehab-tokens.json');
blocks.push(' */');
blocks.push('');

blocks.push(...buildBlock(':root,', '--md-sys-color-', tokens.schemes.light, 'light scheme'));
blocks.push('');

blocks.push(...buildBlock('[data-theme="light"]', '--md-sys-color-', tokens.schemes.light, ''));
blocks.push('');

if (tokens.surfaces?.light) {
  // M3 surfaces are part of the schemes object in this format
  // They are already merged in
}

blocks.push(...buildBlock('[data-theme="dark"]', '--md-sys-color-', tokens.schemes.dark, 'dark scheme'));
blocks.push('');

if (tokens.fixedAccents) {
  blocks.push('/* Fixed accents — identical in light and dark. */');
  for (const [role, value] of Object.entries(tokens.fixedAccents)) {
    if (role.startsWith('_')) continue;
    blocks.push(`--md-sys-color-${kebab(role)}: ${value};`);
  }
}

writeFileSync(cssOut, blocks.join('\n') + '\n', 'utf8');
console.log(`✓ Wrote ${cssOut}`);

// Typed declarations
const dtsLines: string[] = [];
dtsLines.push('export {};');
dtsLines.push('declare const tokensCss: string;');
dtsLines.push('export default tokensCss;');
writeFileSync(dtsOut, dtsLines.join('\n') + '\n', 'utf8');
console.log(`✓ Wrote ${dtsOut}`);

console.log('\nDone. Run `npm run dev --workspace=@rehab/web` to preview.');
